# Generated by Django 4.1.1 on 2024-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0028_salesorder_doc_upload_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='tax_amount_igst',
            new_name='tax_amount',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='igst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
