# Generated by Django 4.1.1 on 2024-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0029_rename_tax_amount_igst_saleorder_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitems',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
