# Generated by Django 4.1.1 on 2024-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0030_alter_salesorderitems_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
