# Generated by Django 4.1.1 on 2024-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0031_alter_saleorder_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderhistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
